learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name='basic_app'
urlpatterns=[
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
    url(r'^about/$',views.about,name='about'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.user_login,name='user_login'),
    url(r'^logout/$',views.user_logout,name='user_logout'),
    url(r'^special/$',views.special,name='special'),


]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import url, include



urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
    url(r'^login/$',views.user_login,name='user_login'),
    url(r'^logout/$',views.user_logout,name='user_logout'),
    url(r'^special/$',views.special,name='special'),


]

learning_templates/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    porfolio_site=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics' , blank=True)

    def __str__(self):
        return self.user.username

learning_templates/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model=User
        fields=('username', 'email', 'password')
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo
        fields=('porfolio_site','profile_pic')

learning_templates/basic_app/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from basic_app.forms import UserForm, UserProfileInfoForm

# log in
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout


# Create your views here.


def index(request):
    return render(request,'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse('You are logged in, welcome!')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_template.html')

def about(request):
    return render(request,'basic_app/about.html')

def register(request):
    registered=False
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()

            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileInfoForm()

    return render(request,'basic_app/registration.html',
                        {'user_form':user_form,
                        'profile_form':profile_form,
                        'registered':registered}
                            )
def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')

        user=authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account not active')
        else:
            print('some one try to use your user name')
            print('username: {} and password {}'.format(username,password))
            return HttpResponse('invalid log in details')
    else:
        return render(request,'basic_app/login.html')

learning_templates/templates/basic_app/about.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
    {% block body_block %}
    <h1>THIS IS ABOUT DRMICHAEL PAGE</h1>
    <a href="{% url 'index' %}">RETURN HOME PAGE</a>
    {% endblock %}

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">DOCTOR MICHAEL</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
            <a class="nav-link" href="{% url 'basic_app:about' %}">About me</a>
            <a class="nav-link" href="#">Book Online Appointment </a>
            <a class="nav-link" href="{% url 'basic_app:register' %}">Register </a>


            <a class="nav-link" href=" {% url 'admin:index' %}">Admin's panel </a>

            {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'user_logout' %}">Logout</a> </li>
              {% else %}
              <li> <a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login </a> </li>
            {% endif %}

          </div>
        </div>
      </div>
    </nav>
    <div class="container">
       {% block body_block %}

      {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% load static %}
    {% block body_block %}
    {% load %}
    <div class="jumbotron">


    <h1>welcome to index</h1>
    <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</h3>

    </div>
        {% endblock %}

learning_templates/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% load static %}
    {% block body_block %}
    {% load %}

    <div class="jumbotron">
      <h1>Please login </h1>
      <form  action="{% url 'basic_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">User name</label>
        <input type="text" name="username" value="Enter username">
        <br>
        <label for="Password">Password: </label>
        <input type="password" name="password" >
        <input type="submit" name="" value="Login">
      </form>

    </div>
        {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %}
    {% block body_block %}
     <h1>welcome to other</h1>
     <h2> this is example of block accesskey=""</h2>

     <p> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
     
     {% endblock %}

learning_templates/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}
    {% block body_block %}
    {% load %}

    <h1>this is register page</h1>
    <div class="jumbotron">

      {% if registered %}
      <h1>Thank you for registered! </h1>


      {% else %}
      <h1>Register here!</h1>

      <h3>fill out the form</h3>

      <form  enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Regiter">

      </form>

      {% endif %}

    </div>

        {% endblock %}

learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>welcome to templates URL </h1>

    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>

  </body>
</html>